AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Call the AWS Lambda API
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Layers:
        - !Ref libs
      Events:
        Create:
          Type: Api
          Properties:
            Auth:
              Authorizer: null
            Path: '/dbcreate'
            Method: post
        Put:
          Type: Api
          Properties:
            Auth:
              Authorizer: null
            Path: '/dbput'
            Method: put
        Delete:
          Type: Api
          Properties:
            Auth:
              Authorizer: null
            Path: '/dbdelete'
            Method: delete
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-s3-lifecycle-lib
      Description: Dependencies for the aws-s3-lifecycle sample app.
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.8
